### ISSUE TITLE
Unable to read Galp_setup

### ISSUE THREAD

**Issue by varunck** [algogp/Galp#1]
Hi Algogp,

Thanks for putting the wonderful scripts together. I tried to run your code and was not able to get it work. I am getting quite a few errors in reading GalpSetup.xlsx file.  I have used the parameters mentioned in cell comments  and replaced it with example strategy and signals but no joy. Do you have any updates to the code? Are you able share working sample strategy and setup file? At the moment i am struck with below errors:

>> Galp.start
Market data farm connection is OK:usfuture
Market data farm connection is OK:jfarm
Market data farm connection is OK:cashfarm
Market data farm connection is OK:usopt
Market data farm connection is OK:usfarm
HMDS data farm connection is OK:ushmds
Index exceeds the number of array elements (1).
Error in Galp_setup (line 73)
    ibContract = GeneralUtils.makeIbDelta1Contract(ib.Handle,ccyArr{1},secType,exchangeName,ccyArr{2});

Error in Galp.start (line 9)
                Galp_setup; 
Error while evaluating TimerFcn for timer 'timer-1' 

Authentication failed.

Can you please help?

Best Regards,
Varun

**Comment by algogp** [comment]
Due to incorrect spreadsheet setup
